### GET - List users
GET http://localhost:3000/users
Accept: application/json

###

### GET - Find a user by id
GET http://localhost:3000/users/2
Accept: application/json

###

### POST - Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Alice"
}